server:
  port: 8080


spring:
  application:
    name: yesbuter-backend
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/yesbuter
    driver-class-name: com.mysql.cj.jdbc.Driver


management:
  endpoints:
    web:
      exposure:
        include=*:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8024/eureka/


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.yesbuter.demo.vo
#mapper-locations: classpath*:**/mapper/*Mapper.xml



